-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2022-11-26 16:31:42 CET
--   site:      Oracle Database 12cR2
--   type:      Oracle Database 12cR2

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE attribute_types (
    attribute_type_id       VARCHAR2(50)
        CONSTRAINT nnc_attribute_types_attribute_type_id NOT NULL,
    attribute_type_name     VARCHAR2(50),
    attirbute_type_category VARCHAR2(50)
)
LOGGING;

ALTER TABLE attribute_types ADD CONSTRAINT attribute_types_pk PRIMARY KEY ( attribute_type_id );

CREATE TABLE attributes (
    attribute_type_id VARCHAR2(50) NOT NULL,
    device_id         VARCHAR2(50) NOT NULL,
    attribute_value   VARCHAR2(50)
)
LOGGING;

ALTER TABLE attributes ADD CONSTRAINT attributes_pk PRIMARY KEY ( device_id,
                                                                  attribute_type_id );

CREATE TABLE connections (
    connection_from VARCHAR2(50) NOT NULL,
    connection_to   VARCHAR2(50) NOT NULL
)
LOGGING;

CREATE TABLE devices (
    device_id       VARCHAR2(50 CHAR)
        CONSTRAINT nnc_devices_device_id NOT NULL,
    device_name     VARCHAR2(50 BYTE)
        CONSTRAINT nnc_devices_device_name NOT NULL,
    device_category VARCHAR2(50 BYTE),
    device_type     VARCHAR2(50)
        CONSTRAINT nnc_devices_device_type NOT NULL
)
LOGGING;

COMMENT ON COLUMN devices.device_id IS
    'universal device identity ';

CREATE INDEX devices_id_parent_idx ON
    devices (
        device_id
    ASC )
        LOGGING;

CREATE INDEX devices_name_idx ON
    devices (
        device_name
    ASC )
        LOGGING;

ALTER TABLE devices ADD CONSTRAINT devices_pk PRIMARY KEY ( device_id );

ALTER TABLE attributes
    ADD CONSTRAINT attributes_attribute_types_fk FOREIGN KEY ( attribute_type_id )
        REFERENCES attribute_types ( attribute_type_id )
    NOT DEFERRABLE;

ALTER TABLE attributes
    ADD CONSTRAINT attributes_devices_fk FOREIGN KEY ( device_id )
        REFERENCES devices ( device_id )
    NOT DEFERRABLE;
    
CREATE TABLE logs (
    id      NUMBER   NOT NULL,
    date    DATE     NOT NULL,
    logtype    VARCHAR2(50),
    message VARCHAR2(4000) NOT NULL
)
LOGGING;
/