# TODO: fix device POST with seting from body
# TODO: fix device GET

### create device

POST http://localhost:3000/device HTTP/1.1
content-type: application/json

{
    "device_id": "sample36",
    "device_name": "device-name-a1",
    "device_category": "Server",
    "device_type": "Racks"
}

### get devices

GET http://localhost:3000/device HTTP/1.1
content-type: application/json

{
    "device_id": "sample36"
}

### get request selected devices

GET http://localhost:8080/device/A-1 HTTP/1.1
content-type: application/json

{
    "device_id": "tall_turquoise_sheep"
}

### get request selected context

GET http://localhost:8080/device HTTP/1.1
content-type: application/json

{
    "device_name": "tall_turquoise_sheep"
}




