openapi: 3.0.2
info:
  title: API for UltimaInventory
  description: Run CRUD od Device object on Node Express.
  version: 1.0.2
servers:
- url: http://localhost:8080
  description: Ultima Inventory API
paths:
  /device:
    get:
      summary: Get Device Id
      description: Get information about devices.
      operationId: deviceGET
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
              examples:
                "1":
                  value: '"1":1'
      x-swagger-router-controller: Default
    put:
      summary: Insert new device
      description: Create device.
      operationId: devicePUT
      responses:
        "200":
          description: OK
      x-swagger-router-controller: Default
    post:
      summary: Insert new device
      description: Create device.
      operationId: devicePOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Device'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
              examples:
                "1":
                  value: 'aaa'
      x-swagger-router-controller: Default
    delete:
      summary: Insert new device
      description: Create device.
      operationId: deviceDELETE
      responses:
        "200":
          description: OK
      x-swagger-router-controller: Default
  /connections:
    get:
      summary: Server heartbeat operation. Get information about connection between
        Devices.
      description: "This operation shows how to override the global security defined above, as we want to open it up for all users."
      operationId: connectionsGET
      responses:
        "200":
          description: OK
      security: []
      x-swagger-router-controller: Default
  /attributes:
    get:
      summary: Server heartbeat operation. Get information about devices attributes.
      description: "This operation shows how to override the global security defined above, as we want to open it up for all users."
      operationId: attributesGET
      responses:
        "200":
          description: OK
      security: []
      x-swagger-router-controller: Default
  /attributes_types:
    get:
      summary: Server heartbeat operation. Get information about devices attributes
        types.
      description: "This operation shows how to override the global security defined above, as we want to open it up for all users."
      operationId: attributes_typesGET
      responses:
        "200":
          description: OK
      security: []
      x-swagger-router-controller: Default
components:
  schemas:
    Device:
      required:
      - device_id
      type: object
      properties:
        device_id:
          type: string
        device_name:
          type: string
        device_category:
          type: string
        device_type:
          type: string
      example:
        device_name: "device-A1"
        device_id: "91601de6-6e93-11ed-a1eb-0242ac120002"
        device_type: "Server"
        device_category: "Network"
